borg:
    auth_key: "EMPTY"
    auth_preifx: ""
    update_interval: -1
    instances:
      # - endpoint: "http://10.0.0.5:8000"
      #   apikey: "sk‑examplekey123"
      #   models: ["gpt-3.5-turbo", "gpt-3.5-turbo-0125"]

      # - endpoint": "http://10.0.0.6:8000"
      #   apikey: "sk‑anotherkey456"
      #   models: ["gpt-4o", "gpt-4o-mini"]
    k8s_discover:
      # - namespace: vllm-servers
      #   selector: borg/expose=vllm
      #   modelkey: borg/models