{{- if .Values.rbac.create }}
{{- if .Values.rbac.clusterScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "borg.fullname" . }}-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  {{- with .Values.rbac.extraRules }}
{{ toYaml . | indent 2 }}
  {{- end }}
{{- else }}
{{- if not .Values.rbac.namespaces }}
{{- fail "rbac.namespaces must contain at least one namespace when rbac.clusterScoped=false" }}
{{- end }}
{{- range $idx, $namespace := .Values.rbac.namespaces }}
{{- if $idx }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "borg.fullname" $ }}-role
  namespace: {{ $namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  {{- with $.Values.rbac.extraRules }}
{{ toYaml . | indent 2 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
