apiVersion: v1
kind: Service
metadata:
  name: {{ include "borg.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "borg.name" . }}
    chart: {{ include "borg.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "borg.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}