replicaCount: 2

image:
  repository: ghcr.io/undy-io/borg
  tag: edge
  pullPolicy: IfNotPresent

authKeySecret:
  name: borg-auth
  key: BORG_AUTH_KEY

apikeySecrets:
  name: borg-apikeys

config:
  auth_prefix: "BORG:"
  update_interval: 30
  instances:
    - endpoint: http://10.0.0.5:8000
      apikeyEnv: VLLM_APIKEY_1
      models: ["gpt-3.5-turbo"]
  k8s_discover:
    - namespace: default
      selector: borg/expose=vllm
      modelkey: borg/models

ingress:
  enabled: true
  className: "nginx"
  issuer:
    name: pkirules-tls
    kind: Issuer  # Could be ClusterIssuer for other environments
    scope: namespaced  # or "cluster" if you ever switch
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert:
      enabled: true
      subject:
        commonName: borg.example.com
        organizations: []
        organizationalUnits: []
        countries: []
        localities: []
        provinces: []
      altNames: []
  hosts:
    - host: borg.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true
    existingSecret: null
    secretName: ""

service:
  port: 80
  targetPort: 8000