name: Build and Push Docker Image

on:
  push:
    branches: [master]         # per-commit builds
    tags:    ['v*.*.*']        # SemVer release tags
  workflow_dispatch:           # manual runs (optional)

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Derive image tags & OCI labels
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/borg
          flavor: |
            latest=auto
          tags: |
            # ─── Commits to master ───
            type=edge,branch=master
            type=sha,format=short

            # ─── SemVer release tags ───
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}


      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
