name: Helm Chart CI

on:
  push:
    paths:
      - 'charts/**'
      - '.github/workflows/helm.yml'
      - '.helmignore'
  pull_request:
    paths:
      - 'charts/**'
      - '.github/workflows/helm.yml'
      - '.helmignore'
  workflow_dispatch:

jobs:
  helm:
    name: Lint & Package Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.2

      - name: Lint Helm chart
        run: helm lint ./charts/borg

      - name: Validate templates
        run: helm template borg-dev ./charts/borg --debug

      - name: Package chart
        run: |
          mkdir -p dist
          helm package ./charts/borg --destination ./dist

      - name: Check for forbidden files in package
        run: |
          echo "📦 Checking contents of packaged chart..."
          tar -tzf ./dist/*.tgz > files.txt

          if grep -E '(test/|\.env|\.git|\.vscode|\.DS_Store)' files.txt; then
            echo "❌ Forbidden files found in Helm package:"
            cat files.txt
            exit 1
          else
            echo "✅ No forbidden files found in Helm package"
          fi
